# Generated by Django 4.1.1 on 2022-09-19 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='capitan',
        ),
        migrations.AddField(
            model_name='usersinteams',
            name='capitan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersinteams',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
