# Generated by Django 4.1.1 on 2022-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код доступа'),
        ),
    ]
