# Generated by Django 4.1.1 on 2022-09-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0001_initial'),
        ('teams', '0002_remove_team_capitan_usersinteams_capitan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamTags',
        ),
        migrations.AlterField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(blank=True, to='banka_idea.usertags'),
        ),
    ]
