# Generated by Django 4.1.1 on 2022-09-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_options_alter_usersinteams_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код доступа'),
        ),
    ]
