# Generated by Django 4.1.1 on 2022-10-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_user_chat_user1_rename_second_user_chat_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='useravatar',
            field=models.TextField(default=''),
        ),
    ]
