# Generated by Django 4.1.1 on 2022-10-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_useravatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='useravatar',
        ),
    ]
