# Generated by Django 4.1.1 on 2022-09-18 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='achievements', verbose_name='Фото')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('count_to_unlock', models.IntegerField(blank=True, default=0, verbose_name='Очки для открытия')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='UsersAchievments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_score', models.IntegerField(default=0, verbose_name='Очки пользователя')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('achievment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievment', verbose_name='Достижение')),
            ],
            options={
                'verbose_name': 'Пользовательское достижение',
                'verbose_name_plural': 'Пользовательские достижения',
            },
        ),
    ]
