# Generated by Django 4.1.1 on 2022-09-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='achievements')),
                ('description', models.CharField(max_length=100)),
                ('count_to_unlock', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='UsersAchievments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_score', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('achievment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievment')),
            ],
            options={
                'verbose_name': 'Пользовательское достижение',
                'verbose_name_plural': 'Пользовательские достижения',
            },
        ),
    ]
