# Generated by Django 4.1.1 on 2022-09-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievment',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='usersachievments',
            options={'verbose_name': 'Пользовательское достижение', 'verbose_name_plural': 'Пользовательские достижения'},
        ),
        migrations.RenameField(
            model_name='usersachievments',
            old_name='achiev',
            new_name='achievment',
        ),
    ]
