# Generated by Django 4.1.1 on 2022-09-14 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='count_to_unlock',
            field=models.IntegerField(blank=True, default=0, verbose_name='Очки для открытия'),
        ),
        migrations.AlterField(
            model_name='achievment',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievment',
            name='image',
            field=models.ImageField(upload_to='achievements', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='achievment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='usersachievments',
            name='achievment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievment', verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='usersachievments',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usersachievments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersachievments',
            name='users_score',
            field=models.IntegerField(default=0, verbose_name='Очки пользователя'),
        ),
    ]
