# Generated by Django 4.1.1 on 2022-10-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievment',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Список достижений'},
        ),
    ]
