# Generated by Django 4.1.1 on 2022-09-18 20:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banka_idea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='comands/avatar')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitan', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banka_idea.idea')),
            ],
        ),
        migrations.CreateModel(
            name='ComandTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInComands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comands.comand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comand',
            name='tags',
            field=models.ManyToManyField(blank=True, to='comands.comandtags'),
        ),
    ]
