# Generated by Django 4.1.1 on 2022-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Solution',
        ),
        migrations.RemoveField(
            model_name='useridealike',
            name='solution',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
