# Generated by Django 4.1.1 on 2022-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, upload_to='solutions'),
        ),
    ]
