# Generated by Django 4.1.1 on 2022-09-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
