# Generated by Django 4.1.1 on 2022-09-14 17:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0002_solution_date_alter_solution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridealike',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='banka_idea.ideatags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.ImageField(blank=True, upload_to='solutions', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='url_to_upload',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatar', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг пользователя'),
        ),
        migrations.AlterField(
            model_name='useridealike',
            name='checked_idea',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
