# Generated by Django 4.1.1 on 2022-09-17 15:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0002_rename_comments_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
