# Generated by Django 4.1.1 on 2022-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0003_useridealike_date_alter_idea_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
