# Generated by Django 4.1.1 on 2022-10-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banka_idea', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='usertags',
            options={'verbose_name': 'Тег пользователя', 'verbose_name_plural': 'Теги пользователей'},
        ),
    ]
